const footerTwo = [
    {
        title:"购物指南",
        list:[
            {
                name:'免费注册',
                url:''
            },
            {
                name:'开通支付宝',
                url:''
            },
            {
                name:'支付宝充值',
                url:''
            },
        ]
    },
    {
        title:"天猫保障",
        list:[
            {
                name:'发票保障',
                url:''
            },
            {
                name:'售后规则',
                url:''
            },
            {
                name:'物流时效保障',
                url:''
            },
        ]
    },
    {
        title:"支付方式",
        list:[
            {
                name:'快捷支付',
                url:''
            },
            {
                name:'信用卡',
                url:''
            },
            {
                name:'余额宝',
                url:''
            },
            {
                name:'蚂蚁花呗',
                url:''
            },
        ]
    },
    {
        title:"商家服务",
        list:[
            {
                name:'天猫规则',
                url:''
            },
            {
                name:'商家入驻',
                url:''
            },
            {
                name:'商家中心',
                url:''
            },
            {
                name:'天猫必修课',
                url:''
            },
            {
                name:'喵言喵语',
                url:''
            },
            {
                name:'平台服务协议',
                url:''
            },
        ]
    }
]

export {footerTwo}