const productList = [
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒',
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    }
]
const interList = [
    {
        onlyImg:true,
        img:require('@/assets/img/onlyImg.png'),
        url:'',
    },
    {
        img:require('@/assets/img/textImg.png'),
        url:'',
        text:'补水舒缓面膜礼盒',
        Subheading:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        onlyImg:true,
        img:require('@/assets/img/onlyImg.png'),
        url:'',
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    }
]

const hobbyList = [
    {
        img:require('@/assets/img/hobby.jpg'),
        url:'',
        price:'59',
        text:'优衣库 男装 罗纹背心(打底纯色） 444998 UNIQLO'
    },
    {
        img:require('@/assets/img/textImg.png'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    },
    {
        img:require('@/assets/img/productDrawing.jpg'),
        url:'',
        price:'59',
        text:'补水舒缓面膜礼盒'
    }
]

export {productList, interList, hobbyList}