const typeList = [
    {
        icon:"icon-nvzhuang",
        children:[
            {
                name:'女装',
                url:''
            },
            {
                name:'内衣',
                url:''
            },
        ]
    },
    {
        icon:"icon-nanzhuang",
        children:[
            {
                name:'男装',
                url:''
            },
            {
                name:'运动户外',
                url:''
            },
        ]
    },
    {
        icon:"icon-xie",
        children:[
            {
                name:'女鞋',
                url:''
            },
            {
                name:'男鞋',
                url:''
            },
            {
                name:'箱包',
                url:''
            },
        ]
    },
    {
        icon:"icon-huazhuangpin",
        children:[
            {
                name:'美妆',
                url:''
            },
            {
                name:'个人护理',
                url:''
            },
        ]
    },
    {
        icon:"icon-diamond-o",
        children:[
            {
                name:'腕表',
                url:''
            },
            {
                name:'眼镜',
                url:''
            },
            {
                name:'珠宝饰品',
                url:''
            },
        ]
    },
    {
        icon:"icon-shouji1",
        children:[
            {
                name:'手机',
                url:''
            },
            {
                name:'数码',
                url:''
            },
            {
                name:'电脑办公',
                url:''
            },
        ]
    },
    {
        icon:"icon-muyingwanju",
        children:[
            {
                name:'母婴玩具',
                url:''
            }
        ]
    },
    {
        icon:"icon-shipin",
        children:[
            {
                name:'零食',
                url:''
            },
            {
                name:'茶酒',
                url:''
            },
            {
                name:'进口食品',
                url:''
            },
        ]
    },
    {
        icon:"icon-alishangchuan-",
        children:[
            {
                name:'生鲜水果',
                url:''
            }
        ]
    },
    {
        icon:"icon-jiayongdianqi",
        children:[
            {
                name:'大家电',
                url:''
            },
            {
                name:'生活电器',
                url:''
            },
        ]
    },
    {
        icon:"icon-jiajujiancai",
        children:[
            {
                name:'家具',
                url:''
            },
            {
                name:'灯具',
                url:''
            },
            {
                name:'卫浴',
                url:''
            },
        ]
    },
    {
        icon:"icon-qichepeijian",
        children:[
            {
                name:'汽车',
                url:''
            },
            {
                name:'配件',
                url:''
            },
            {
                name:'用品',
                url:''
            },
        ]
    },
    {
        icon:"icon-jiafangjiashi",
        children:[
            {
                name:'家纺',
                url:''
            },
            {
                name:'家饰',
                url:''
            },
            {
                name:'鲜花',
                url:''
            },
        ]
    },
    {
        icon:"icon-yiyaobaojian",
        children:[
            {
                name:'医药保健',
                url:''
            }
        ]
    },
    {
        icon:"icon-kafei",
        children:[
            {
                name:'厨具',
                url:''
            },
            {
                name:'收纳',
                url:''
            },
            {
                name:'宠物',
                url:''
            },
        ]
    },
    {
        icon:"icon-yingyinyule",
        children:[
            {
                name:'图书音像',
                url:''
            }
        ]
    },
]

const topList = [
    {
        name:'天猫国际',
        img:require('@/assets/img/tianmaoguoji.jpg'),
        url:''
    },
    {
        name:'特卖专场',
        img:require('@/assets/img/temaizhuanchang.jpg'),
        url:''
    },
    {
        name:'天猫',
        img:require('@/assets/img/tianmao.jpg'),
        url:''
    },
    {
        name:'潮流名店',
        img:require('@/assets/img/chaoliumingdian.jpg'),
        url:''
    },
    {
        name:'绿色节能',
        img:require('@/assets/img/lvsejieneng.jpg'),
        url:''
    }
]
const bottomList = {
    'one': [
        {
            name:'天猫国际',
            img:require('@/assets/img/tianmaoguoji.jpg'),
            url:''
        },
        {
            name:'特卖专场',
            img:require('@/assets/img/temaizhuanchang.jpg'),
            url:''
        }
    ],
    'two':[
        {
            name:'天猫',
            img:require('@/assets/img/tianmao.jpg'),
            url:''
        },
        {
            name:'潮流名店',
            img:require('@/assets/img/chaoliumingdian.jpg'),
            url:''
        }
    ],
    'three':[
        {
            name:'绿色节能',
            img:require('@/assets/img/lvsejieneng.jpg'),
            url:''
        },
        {
            name:'绿色节能',
            img:require('@/assets/img/lvsejieneng.jpg'),
            url:''
        }
    ]
}

export {typeList, topList, bottomList}